name: mobile_version
description: "A new Flutter project."


version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2  # For making API requests
  shared_preferences: ^2.0.6


  cupertino_icons: ^1.0.6
  flutter_staggered_animations: ^1.1.1
  carousel_slider: ^5.0.0
  font_awesome_icon_class: ^0.0.6
  font_awesome_flutter: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:

 
  uses-material-design: true

  assets:
    - images/

  